# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chatapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1368, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1800, 1000))
        MainWindow.setBaseSize(QtCore.QSize(1368, 1000))
        MainWindow.setStyleSheet("font-family: \'Open Sans\';")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1368, 1000))
        self.centralwidget.setStyleSheet("\n"
"background-color:#ffffff;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu_widget = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu_widget.setMinimumSize(QtCore.QSize(360, 0))
        self.leftMenu_widget.setMaximumSize(QtCore.QSize(360, 16777215))
        self.leftMenu_widget.setStyleSheet("#leftMenu_widget{\n"
"border-right: 1px solid #E1E5EA;\n"
"font-family: Inter;\n"
"}")
        self.leftMenu_widget.setObjectName("leftMenu_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenu_widget)
        self.verticalLayout.setContentsMargins(0, 0, 2, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_widget_2 = QtWidgets.QWidget(self.leftMenu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_widget_2.sizePolicy().hasHeightForWidth())
        self.search_widget_2.setSizePolicy(sizePolicy)
        self.search_widget_2.setMinimumSize(QtCore.QSize(350, 80))
        self.search_widget_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.search_widget_2.setStyleSheet("")
        self.search_widget_2.setObjectName("search_widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.search_widget_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.accountButton = QtWidgets.QPushButton(self.search_widget_2)
        self.accountButton.setMinimumSize(QtCore.QSize(40, 40))
        self.accountButton.setMaximumSize(QtCore.QSize(40, 40))
        self.accountButton.setStyleSheet("background: transparent;\n"
"borders: none;")
        self.accountButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountButton.setIcon(icon)
        self.accountButton.setIconSize(QtCore.QSize(40, 40))
        self.accountButton.setObjectName("accountButton")
        self.horizontalLayout_2.addWidget(self.accountButton)
        self.label_2 = QtWidgets.QLabel(self.search_widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(40, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font-size: 24px;\n"
"font-weight: 600;\n"
"line-height: 36px;\n"
"text-align: left;\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.search_widget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.widget_4 = QtWidgets.QWidget(self.leftMenu_widget)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_4.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"background:#F6F6F9;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.addimageButton = QtWidgets.QPushButton(self.widget_4)
        self.addimageButton.setMinimumSize(QtCore.QSize(40, 40))
        self.addimageButton.setMaximumSize(QtCore.QSize(40, 40))
        self.addimageButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-add-file-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addimageButton.setIcon(icon1)
        self.addimageButton.setIconSize(QtCore.QSize(40, 40))
        self.addimageButton.setObjectName("addimageButton")
        self.horizontalLayout_11.addWidget(self.addimageButton)
        self.logoutButton = QtWidgets.QPushButton(self.widget_4)
        self.logoutButton.setMinimumSize(QtCore.QSize(40, 40))
        self.logoutButton.setMaximumSize(QtCore.QSize(40, 40))
        self.logoutButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-logout-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon2)
        self.logoutButton.setIconSize(QtCore.QSize(40, 40))
        self.logoutButton.setObjectName("logoutButton")
        self.horizontalLayout_11.addWidget(self.logoutButton)
        self.hideButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hideButton.sizePolicy().hasHeightForWidth())
        self.hideButton.setSizePolicy(sizePolicy)
        self.hideButton.setMinimumSize(QtCore.QSize(40, 40))
        self.hideButton.setMaximumSize(QtCore.QSize(40, 40))
        self.hideButton.setStyleSheet("background: transparent;\n"
"borders: none;")
        self.hideButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-hide-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hideButton.setIcon(icon3)
        self.hideButton.setIconSize(QtCore.QSize(40, 40))
        self.hideButton.setObjectName("hideButton")
        self.horizontalLayout_11.addWidget(self.hideButton)
        self.verticalLayout.addWidget(self.widget_4)
        self.chatList_widget = QtWidgets.QWidget(self.leftMenu_widget)
        self.chatList_widget.setStyleSheet("font-family: Inter;\n"
"")
        self.chatList_widget.setObjectName("chatList_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.chatList_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.promo_widget = QtWidgets.QWidget(self.chatList_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.promo_widget.sizePolicy().hasHeightForWidth())
        self.promo_widget.setSizePolicy(sizePolicy)
        self.promo_widget.setMinimumSize(QtCore.QSize(0, 90))
        self.promo_widget.setStyleSheet("")
        self.promo_widget.setObjectName("promo_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.promo_widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.promoButton = QtWidgets.QPushButton(self.promo_widget)
        self.promoButton.setMinimumSize(QtCore.QSize(360, 90))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        self.promoButton.setFont(font)
        self.promoButton.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"text-align: left;\n"
"padding:20px;\n"
"}\n"
"QPushButton::hover{\n"
"background: #EBFFED;\n"
"cursor: pointinghand;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/avatar (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.promoButton.setIcon(icon4)
        self.promoButton.setIconSize(QtCore.QSize(60, 60))
        self.promoButton.setObjectName("promoButton")
        self.horizontalLayout_6.addWidget(self.promoButton)
        self.verticalLayout_3.addWidget(self.promo_widget, 0, QtCore.Qt.AlignVCenter)
        self.groupe_widget = QtWidgets.QWidget(self.chatList_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupe_widget.sizePolicy().hasHeightForWidth())
        self.groupe_widget.setSizePolicy(sizePolicy)
        self.groupe_widget.setMinimumSize(QtCore.QSize(0, 90))
        self.groupe_widget.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"text-align: left;\n"
"padding:20px;\n"
"}\n"
"QPushButton::hover{\n"
"background: #EBFFED;\n"
"cursor: pointinghand;\n"
"}")
        self.groupe_widget.setObjectName("groupe_widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupe_widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupeButton = QtWidgets.QPushButton(self.groupe_widget)
        self.groupeButton.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        self.groupeButton.setFont(font)
        self.groupeButton.setIcon(icon4)
        self.groupeButton.setIconSize(QtCore.QSize(60, 60))
        self.groupeButton.setObjectName("groupeButton")
        self.horizontalLayout_7.addWidget(self.groupeButton)
        self.verticalLayout_3.addWidget(self.groupe_widget)
        self.lobby_widget = QtWidgets.QWidget(self.chatList_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_widget.sizePolicy().hasHeightForWidth())
        self.lobby_widget.setSizePolicy(sizePolicy)
        self.lobby_widget.setMinimumSize(QtCore.QSize(0, 90))
        self.lobby_widget.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"text-align: left;\n"
"padding:20px;\n"
"}\n"
"QPushButton::hover{\n"
"background: #EBFFED;\n"
"cursor: pointinghand;\n"
"}")
        self.lobby_widget.setObjectName("lobby_widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.lobby_widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lobbybutton = QtWidgets.QPushButton(self.lobby_widget)
        self.lobbybutton.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        self.lobbybutton.setFont(font)
        self.lobbybutton.setIcon(icon4)
        self.lobbybutton.setIconSize(QtCore.QSize(60, 60))
        self.lobbybutton.setObjectName("lobbybutton")
        self.horizontalLayout_8.addWidget(self.lobbybutton)
        self.verticalLayout_3.addWidget(self.lobby_widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.chatList_widget)
        self.chatList_widget.raise_()
        self.search_widget_2.raise_()
        self.widget_4.raise_()
        self.horizontalLayout.addWidget(self.leftMenu_widget)
        self.mainChat_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainChat_widget.sizePolicy().hasHeightForWidth())
        self.mainChat_widget.setSizePolicy(sizePolicy)
        self.mainChat_widget.setMinimumSize(QtCore.QSize(1008, 0))
        self.mainChat_widget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.mainChat_widget.setStyleSheet("#mainChat_widget{\n"
"border-right: 1px solid #E1E5EA;\n"
"}")
        self.mainChat_widget.setObjectName("mainChat_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainChat_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_widget = QtWidgets.QWidget(self.mainChat_widget)
        self.search_widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.search_widget.setStyleSheet("#search_widget{\n"
"border-bottom: 1px solid #E1E5EA;\n"
"}\n"
"")
        self.search_widget.setObjectName("search_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search_widget)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.profilepic = QtWidgets.QLabel(self.search_widget)
        self.profilepic.setMinimumSize(QtCore.QSize(40, 40))
        self.profilepic.setMaximumSize(QtCore.QSize(40, 40))
        self.profilepic.setText("")
        self.profilepic.setPixmap(QtGui.QPixmap(":/icons/icons/avatar.png"))
        self.profilepic.setObjectName("profilepic")
        self.horizontalLayout_3.addWidget(self.profilepic)
        self.searchbar = QtWidgets.QLineEdit(self.search_widget)
        self.searchbar.setMinimumSize(QtCore.QSize(768, 60))
        self.searchbar.setMaximumSize(QtCore.QSize(768, 60))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.searchbar.setFont(font)
        self.searchbar.setStyleSheet("background-color: #F6F7F9;\n"
"border:12px;\n"
"border-radius: 8px;\n"
"color:929FB1;\n"
"padding-left: 10px;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-weight: 400;\n"
"line-height: 24px;\n"
"text-align: left;\n"
"")
        self.searchbar.setObjectName("searchbar")
        self.horizontalLayout_3.addWidget(self.searchbar)
        self.searchbutton = QtWidgets.QPushButton(self.search_widget)
        self.searchbutton.setMinimumSize(QtCore.QSize(40, 40))
        self.searchbutton.setMaximumSize(QtCore.QSize(40, 40))
        self.searchbutton.setStyleSheet("background: transparent;\n"
"borders: none;")
        self.searchbutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchbutton.setIcon(icon5)
        self.searchbutton.setIconSize(QtCore.QSize(24, 24))
        self.searchbutton.setObjectName("searchbutton")
        self.horizontalLayout_3.addWidget(self.searchbutton)
        self.detailsMenuButton = QtWidgets.QPushButton(self.search_widget)
        self.detailsMenuButton.setMinimumSize(QtCore.QSize(40, 40))
        self.detailsMenuButton.setMaximumSize(QtCore.QSize(40, 40))
        self.detailsMenuButton.setStyleSheet("background: transparent;\n"
"borders: none;\n"
"padding-right:20px;")
        self.detailsMenuButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/Icon-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detailsMenuButton.setIcon(icon6)
        self.detailsMenuButton.setIconSize(QtCore.QSize(40, 40))
        self.detailsMenuButton.setObjectName("detailsMenuButton")
        self.horizontalLayout_3.addWidget(self.detailsMenuButton)
        self.verticalLayout_2.addWidget(self.search_widget)
        self.chats_stackedwidget = QtWidgets.QStackedWidget(self.mainChat_widget)
        self.chats_stackedwidget.setStyleSheet("background: #F6F6F9")
        self.chats_stackedwidget.setObjectName("chats_stackedwidget")
        self.promopage = QtWidgets.QWidget()
        self.promopage.setObjectName("promopage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.promopage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.promoscrollarea = QtWidgets.QScrollArea(self.promopage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.promoscrollarea.sizePolicy().hasHeightForWidth())
        self.promoscrollarea.setSizePolicy(sizePolicy)
        self.promoscrollarea.setMinimumSize(QtCore.QSize(1008, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.promoscrollarea.setPalette(palette)
        self.promoscrollarea.setStyleSheet("*{\n"
"background: #F6F6F9;\n"
"border:none;\n"
"\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px; /* Adjust the width as needed */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #E1E5EA;\n"
"    min-height: 20px; /* Adjust the handle size as needed */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.promoscrollarea.setWidgetResizable(True)
        self.promoscrollarea.setObjectName("promoscrollarea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 998, 885))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sendermessageFrame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.sendermessageFrame_2.setMinimumSize(QtCore.QSize(0, 90))
        self.sendermessageFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendermessageFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendermessageFrame_2.setObjectName("sendermessageFrame_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.sendermessageFrame_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.sendermessagebodyFrame_2 = QtWidgets.QFrame(self.sendermessageFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendermessagebodyFrame_2.sizePolicy().hasHeightForWidth())
        self.sendermessagebodyFrame_2.setSizePolicy(sizePolicy)
        self.sendermessagebodyFrame_2.setMinimumSize(QtCore.QSize(467, 50))
        self.sendermessagebodyFrame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendermessagebodyFrame_2.setBaseSize(QtCore.QSize(467, 50))
        self.sendermessagebodyFrame_2.setStyleSheet("background-color: #EBFFED;\n"
"top: 18px;\n"
"left: 540px;\n"
"padding: 8px 12px 8px 12px;\n"
"\n"
"border-radius: 16px;\n"
"border-bottom-right-radius: 0px;\n"
"\n"
"")
        self.sendermessagebodyFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendermessagebodyFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendermessagebodyFrame_2.setObjectName("sendermessagebodyFrame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.sendermessagebodyFrame_2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setVerticalSpacing(3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.sendermessagetext_2 = QtWidgets.QLabel(self.sendermessagebodyFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendermessagetext_2.sizePolicy().hasHeightForWidth())
        self.sendermessagetext_2.setSizePolicy(sizePolicy)
        self.sendermessagetext_2.setMinimumSize(QtCore.QSize(443, 50))
        self.sendermessagetext_2.setMaximumSize(QtCore.QSize(592, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.sendermessagetext_2.setFont(font)
        self.sendermessagetext_2.setStyleSheet("background-color: transparent;\n"
"color:#181D25;\n"
"\n"
"")
        self.sendermessagetext_2.setWordWrap(True)
        self.sendermessagetext_2.setObjectName("sendermessagetext_2")
        self.gridLayout_8.addWidget(self.sendermessagetext_2, 0, 0, 1, 1)
        self.sendermessagetime_2 = QtWidgets.QLabel(self.sendermessagebodyFrame_2)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.sendermessagetime_2.setFont(font)
        self.sendermessagetime_2.setStyleSheet("background:transparent;\n"
"color:#929FB1;\n"
"padding:0;")
        self.sendermessagetime_2.setObjectName("sendermessagetime_2")
        self.gridLayout_8.addWidget(self.sendermessagetime_2, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_13.addWidget(self.sendermessagebodyFrame_2, 0, QtCore.Qt.AlignRight)
        self.senderpic_2 = QtWidgets.QLabel(self.sendermessageFrame_2)
        self.senderpic_2.setMinimumSize(QtCore.QSize(56, 56))
        self.senderpic_2.setMaximumSize(QtCore.QSize(56, 56))
        self.senderpic_2.setText("")
        self.senderpic_2.setPixmap(QtGui.QPixmap(":/icons/icons/avatar (1).png"))
        self.senderpic_2.setObjectName("senderpic_2")
        self.horizontalLayout_13.addWidget(self.senderpic_2)
        self.verticalLayout_8.addWidget(self.sendermessageFrame_2)
        self.receivermessageFrame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.receivermessageFrame_2.setMinimumSize(QtCore.QSize(550, 90))
        self.receivermessageFrame_2.setMaximumSize(QtCore.QSize(443, 16777215))
        self.receivermessageFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.receivermessageFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.receivermessageFrame_2.setObjectName("receivermessageFrame_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.receivermessageFrame_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.senderpic_4 = QtWidgets.QLabel(self.receivermessageFrame_2)
        self.senderpic_4.setMinimumSize(QtCore.QSize(56, 56))
        self.senderpic_4.setMaximumSize(QtCore.QSize(56, 56))
        self.senderpic_4.setText("")
        self.senderpic_4.setPixmap(QtGui.QPixmap(":/icons/icons/avatar (1).png"))
        self.senderpic_4.setObjectName("senderpic_4")
        self.horizontalLayout_14.addWidget(self.senderpic_4)
        self.receivermessagebodyFrame_2 = QtWidgets.QFrame(self.receivermessageFrame_2)
        self.receivermessagebodyFrame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.receivermessagebodyFrame_2.setMaximumSize(QtCore.QSize(592, 16777215))
        self.receivermessagebodyFrame_2.setStyleSheet("background-color: #FFFFFF;\n"
"top: 618px;\n"
"left: 86px;\n"
"padding: 8px 12px 8px 12px;\n"
"\n"
"border-radius: 16px;\n"
"border-bottom-left-radius: 0px;\n"
"")
        self.receivermessagebodyFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.receivermessagebodyFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.receivermessagebodyFrame_2.setObjectName("receivermessagebodyFrame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.receivermessagebodyFrame_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setVerticalSpacing(3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.receivermessagetime_2 = QtWidgets.QLabel(self.receivermessagebodyFrame_2)
        self.receivermessagetime_2.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.receivermessagetime_2.setFont(font)
        self.receivermessagetime_2.setStyleSheet("background:transparent;\n"
"color:#929FB1;\n"
"padding:0;")
        self.receivermessagetime_2.setObjectName("receivermessagetime_2")
        self.gridLayout_9.addWidget(self.receivermessagetime_2, 1, 1, 1, 1)
        self.receivermessagetext_2 = QtWidgets.QLabel(self.receivermessagebodyFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivermessagetext_2.sizePolicy().hasHeightForWidth())
        self.receivermessagetext_2.setSizePolicy(sizePolicy)
        self.receivermessagetext_2.setMinimumSize(QtCore.QSize(443, 40))
        self.receivermessagetext_2.setMaximumSize(QtCore.QSize(592, 500))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.receivermessagetext_2.setFont(font)
        self.receivermessagetext_2.setStyleSheet("background-color: transparent;\n"
"color:#181D25;\n"
"")
        self.receivermessagetext_2.setWordWrap(True)
        self.receivermessagetext_2.setObjectName("receivermessagetext_2")
        self.gridLayout_9.addWidget(self.receivermessagetext_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_14.addWidget(self.receivermessagebodyFrame_2)
        self.verticalLayout_8.addWidget(self.receivermessageFrame_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 597, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.promoscrollarea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.promoscrollarea)
        self.chats_stackedwidget.addWidget(self.promopage)
        self.grouppage = QtWidgets.QWidget()
        self.grouppage.setObjectName("grouppage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.grouppage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupescrollarea = QtWidgets.QScrollArea(self.grouppage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupescrollarea.sizePolicy().hasHeightForWidth())
        self.groupescrollarea.setSizePolicy(sizePolicy)
        self.groupescrollarea.setMinimumSize(QtCore.QSize(1008, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupescrollarea.setPalette(palette)
        self.groupescrollarea.setStyleSheet("*{\n"
"background: #F6F6F9;\n"
"border:none;\n"
"\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px; /* Adjust the width as needed */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #E1E5EA;\n"
"    min-height: 20px; /* Adjust the handle size as needed */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.groupescrollarea.setWidgetResizable(True)
        self.groupescrollarea.setObjectName("groupescrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 998, 885))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sendermessageFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.sendermessageFrame.setMinimumSize(QtCore.QSize(0, 90))
        self.sendermessageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendermessageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendermessageFrame.setObjectName("sendermessageFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.sendermessageFrame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sendermessagebodyFrame = QtWidgets.QFrame(self.sendermessageFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendermessagebodyFrame.sizePolicy().hasHeightForWidth())
        self.sendermessagebodyFrame.setSizePolicy(sizePolicy)
        self.sendermessagebodyFrame.setMinimumSize(QtCore.QSize(467, 50))
        self.sendermessagebodyFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendermessagebodyFrame.setBaseSize(QtCore.QSize(467, 50))
        self.sendermessagebodyFrame.setStyleSheet("background-color: #EBFFED;\n"
"top: 18px;\n"
"left: 540px;\n"
"padding: 8px 12px 8px 12px;\n"
"\n"
"border-radius: 16px;\n"
"border-bottom-right-radius: 0px;\n"
"\n"
"")
        self.sendermessagebodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendermessagebodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendermessagebodyFrame.setObjectName("sendermessagebodyFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.sendermessagebodyFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sendermessagetext = QtWidgets.QLabel(self.sendermessagebodyFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendermessagetext.sizePolicy().hasHeightForWidth())
        self.sendermessagetext.setSizePolicy(sizePolicy)
        self.sendermessagetext.setMinimumSize(QtCore.QSize(443, 50))
        self.sendermessagetext.setMaximumSize(QtCore.QSize(592, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.sendermessagetext.setFont(font)
        self.sendermessagetext.setStyleSheet("background-color: transparent;\n"
"color:#181D25;\n"
"\n"
"")
        self.sendermessagetext.setWordWrap(True)
        self.sendermessagetext.setObjectName("sendermessagetext")
        self.gridLayout_4.addWidget(self.sendermessagetext, 0, 0, 1, 1)
        self.sendermessagetime = QtWidgets.QLabel(self.sendermessagebodyFrame)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.sendermessagetime.setFont(font)
        self.sendermessagetime.setStyleSheet("background:transparent;\n"
"color:#929FB1;\n"
"padding:0;")
        self.sendermessagetime.setObjectName("sendermessagetime")
        self.gridLayout_4.addWidget(self.sendermessagetime, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_10.addWidget(self.sendermessagebodyFrame, 0, QtCore.Qt.AlignRight)
        self.senderpic = QtWidgets.QLabel(self.sendermessageFrame)
        self.senderpic.setMinimumSize(QtCore.QSize(56, 56))
        self.senderpic.setMaximumSize(QtCore.QSize(56, 56))
        self.senderpic.setText("")
        self.senderpic.setPixmap(QtGui.QPixmap(":/icons/icons/avatar (1).png"))
        self.senderpic.setObjectName("senderpic")
        self.horizontalLayout_10.addWidget(self.senderpic)
        self.verticalLayout_9.addWidget(self.sendermessageFrame)
        self.receivermessageFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.receivermessageFrame.setMinimumSize(QtCore.QSize(550, 90))
        self.receivermessageFrame.setMaximumSize(QtCore.QSize(443, 16777215))
        self.receivermessageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.receivermessageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.receivermessageFrame.setObjectName("receivermessageFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.receivermessageFrame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.senderpic_3 = QtWidgets.QLabel(self.receivermessageFrame)
        self.senderpic_3.setMinimumSize(QtCore.QSize(56, 56))
        self.senderpic_3.setMaximumSize(QtCore.QSize(56, 56))
        self.senderpic_3.setText("")
        self.senderpic_3.setPixmap(QtGui.QPixmap(":/icons/icons/avatar (1).png"))
        self.senderpic_3.setObjectName("senderpic_3")
        self.horizontalLayout_12.addWidget(self.senderpic_3)
        self.receivermessagebodyFrame = QtWidgets.QFrame(self.receivermessageFrame)
        self.receivermessagebodyFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.receivermessagebodyFrame.setMaximumSize(QtCore.QSize(592, 16777215))
        self.receivermessagebodyFrame.setStyleSheet("background-color: #FFFFFF;\n"
"top: 618px;\n"
"left: 86px;\n"
"padding: 8px 12px 8px 12px;\n"
"\n"
"border-radius: 16px;\n"
"border-bottom-left-radius: 0px;\n"
"")
        self.receivermessagebodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.receivermessagebodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.receivermessagebodyFrame.setObjectName("receivermessagebodyFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.receivermessagebodyFrame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setVerticalSpacing(3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.receivermessagetext = QtWidgets.QLabel(self.receivermessagebodyFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivermessagetext.sizePolicy().hasHeightForWidth())
        self.receivermessagetext.setSizePolicy(sizePolicy)
        self.receivermessagetext.setMinimumSize(QtCore.QSize(443, 40))
        self.receivermessagetext.setMaximumSize(QtCore.QSize(592, 500))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.receivermessagetext.setFont(font)
        self.receivermessagetext.setStyleSheet("background-color: transparent;\n"
"color:#181D25;\n"
"")
        self.receivermessagetext.setWordWrap(True)
        self.receivermessagetext.setObjectName("receivermessagetext")
        self.gridLayout_6.addWidget(self.receivermessagetext, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.receivermessagetime = QtWidgets.QLabel(self.receivermessagebodyFrame)
        self.receivermessagetime.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.receivermessagetime.setFont(font)
        self.receivermessagetime.setStyleSheet("background:transparent;\n"
"color:#929FB1;\n"
"padding:0;")
        self.receivermessagetime.setObjectName("receivermessagetime")
        self.gridLayout_6.addWidget(self.receivermessagetime, 1, 1, 1, 1)
        self.horizontalLayout_12.addWidget(self.receivermessagebodyFrame)
        self.verticalLayout_9.addWidget(self.receivermessageFrame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 597, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.groupescrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.groupescrollarea)
        self.chats_stackedwidget.addWidget(self.grouppage)
        self.lobbypage = QtWidgets.QWidget()
        self.lobbypage.setObjectName("lobbypage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.lobbypage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lobbyscrollarea = QtWidgets.QScrollArea(self.lobbypage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobbyscrollarea.sizePolicy().hasHeightForWidth())
        self.lobbyscrollarea.setSizePolicy(sizePolicy)
        self.lobbyscrollarea.setMinimumSize(QtCore.QSize(1008, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lobbyscrollarea.setPalette(palette)
        self.lobbyscrollarea.setStyleSheet("*{\n"
"background: #F6F6F9;\n"
"border:none;\n"
"\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px; /* Adjust the width as needed */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #E1E5EA;\n"
"    min-height: 20px; /* Adjust the handle size as needed */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.lobbyscrollarea.setWidgetResizable(True)
        self.lobbyscrollarea.setObjectName("lobbyscrollarea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 991, 885))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.sendermessageFrame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.sendermessageFrame_3.setMinimumSize(QtCore.QSize(0, 90))
        self.sendermessageFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendermessageFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendermessageFrame_3.setObjectName("sendermessageFrame_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.sendermessageFrame_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.sendermessagebodyFrame_3 = QtWidgets.QFrame(self.sendermessageFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendermessagebodyFrame_3.sizePolicy().hasHeightForWidth())
        self.sendermessagebodyFrame_3.setSizePolicy(sizePolicy)
        self.sendermessagebodyFrame_3.setMinimumSize(QtCore.QSize(467, 50))
        self.sendermessagebodyFrame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendermessagebodyFrame_3.setBaseSize(QtCore.QSize(467, 50))
        self.sendermessagebodyFrame_3.setStyleSheet("background-color: #EBFFED;\n"
"top: 18px;\n"
"left: 540px;\n"
"padding: 8px 12px 8px 12px;\n"
"\n"
"border-radius: 16px;\n"
"border-bottom-right-radius: 0px;\n"
"\n"
"")
        self.sendermessagebodyFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendermessagebodyFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendermessagebodyFrame_3.setObjectName("sendermessagebodyFrame_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.sendermessagebodyFrame_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(0)
        self.gridLayout_10.setVerticalSpacing(3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.sendermessagetext_3 = QtWidgets.QLabel(self.sendermessagebodyFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendermessagetext_3.sizePolicy().hasHeightForWidth())
        self.sendermessagetext_3.setSizePolicy(sizePolicy)
        self.sendermessagetext_3.setMinimumSize(QtCore.QSize(443, 50))
        self.sendermessagetext_3.setMaximumSize(QtCore.QSize(592, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.sendermessagetext_3.setFont(font)
        self.sendermessagetext_3.setStyleSheet("background-color: transparent;\n"
"color:#181D25;\n"
"\n"
"")
        self.sendermessagetext_3.setWordWrap(True)
        self.sendermessagetext_3.setObjectName("sendermessagetext_3")
        self.gridLayout_10.addWidget(self.sendermessagetext_3, 0, 0, 1, 1)
        self.sendermessagetime_3 = QtWidgets.QLabel(self.sendermessagebodyFrame_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.sendermessagetime_3.setFont(font)
        self.sendermessagetime_3.setStyleSheet("background:transparent;\n"
"color:#929FB1;\n"
"padding:0;")
        self.sendermessagetime_3.setObjectName("sendermessagetime_3")
        self.gridLayout_10.addWidget(self.sendermessagetime_3, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_15.addWidget(self.sendermessagebodyFrame_3, 0, QtCore.Qt.AlignRight)
        self.senderpic_5 = QtWidgets.QLabel(self.sendermessageFrame_3)
        self.senderpic_5.setMinimumSize(QtCore.QSize(56, 56))
        self.senderpic_5.setMaximumSize(QtCore.QSize(56, 56))
        self.senderpic_5.setText("")
        self.senderpic_5.setPixmap(QtGui.QPixmap(":/icons/icons/avatar (1).png"))
        self.senderpic_5.setObjectName("senderpic_5")
        self.horizontalLayout_15.addWidget(self.senderpic_5)
        self.verticalLayout_11.addWidget(self.sendermessageFrame_3)
        self.receivermessageFrame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.receivermessageFrame_3.setMinimumSize(QtCore.QSize(550, 90))
        self.receivermessageFrame_3.setMaximumSize(QtCore.QSize(443, 16777215))
        self.receivermessageFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.receivermessageFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.receivermessageFrame_3.setObjectName("receivermessageFrame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.receivermessageFrame_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.senderpic_6 = QtWidgets.QLabel(self.receivermessageFrame_3)
        self.senderpic_6.setMinimumSize(QtCore.QSize(56, 56))
        self.senderpic_6.setMaximumSize(QtCore.QSize(56, 56))
        self.senderpic_6.setText("")
        self.senderpic_6.setPixmap(QtGui.QPixmap(":/icons/icons/avatar (1).png"))
        self.senderpic_6.setObjectName("senderpic_6")
        self.horizontalLayout_16.addWidget(self.senderpic_6)
        self.receivermessagebodyFrame_3 = QtWidgets.QFrame(self.receivermessageFrame_3)
        self.receivermessagebodyFrame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.receivermessagebodyFrame_3.setMaximumSize(QtCore.QSize(592, 16777215))
        self.receivermessagebodyFrame_3.setStyleSheet("background-color: #FFFFFF;\n"
"top: 618px;\n"
"left: 86px;\n"
"padding: 8px 12px 8px 12px;\n"
"\n"
"border-radius: 16px;\n"
"border-bottom-left-radius: 0px;\n"
"")
        self.receivermessagebodyFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.receivermessagebodyFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.receivermessagebodyFrame_3.setObjectName("receivermessagebodyFrame_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.receivermessagebodyFrame_3)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(0)
        self.gridLayout_11.setVerticalSpacing(3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.receivermessagetext_3 = QtWidgets.QLabel(self.receivermessagebodyFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivermessagetext_3.sizePolicy().hasHeightForWidth())
        self.receivermessagetext_3.setSizePolicy(sizePolicy)
        self.receivermessagetext_3.setMinimumSize(QtCore.QSize(443, 40))
        self.receivermessagetext_3.setMaximumSize(QtCore.QSize(592, 500))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.receivermessagetext_3.setFont(font)
        self.receivermessagetext_3.setStyleSheet("background-color: transparent;\n"
"color:#181D25;\n"
"")
        self.receivermessagetext_3.setWordWrap(True)
        self.receivermessagetext_3.setObjectName("receivermessagetext_3")
        self.gridLayout_11.addWidget(self.receivermessagetext_3, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.receivermessagetime_3 = QtWidgets.QLabel(self.receivermessagebodyFrame_3)
        self.receivermessagetime_3.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.receivermessagetime_3.setFont(font)
        self.receivermessagetime_3.setStyleSheet("background:transparent;\n"
"color:#929FB1;\n"
"padding:0;")
        self.receivermessagetime_3.setObjectName("receivermessagetime_3")
        self.gridLayout_11.addWidget(self.receivermessagetime_3, 1, 1, 1, 1)
        self.horizontalLayout_16.addWidget(self.receivermessagebodyFrame_3)
        self.verticalLayout_11.addWidget(self.receivermessageFrame_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 597, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.lobbyscrollarea.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_12.addWidget(self.lobbyscrollarea)
        self.chats_stackedwidget.addWidget(self.lobbypage)
        self.verticalLayout_2.addWidget(self.chats_stackedwidget)
        self.messageInput_widget = QtWidgets.QWidget(self.mainChat_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageInput_widget.sizePolicy().hasHeightForWidth())
        self.messageInput_widget.setSizePolicy(sizePolicy)
        self.messageInput_widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.messageInput_widget.setStyleSheet("#messageInput_widget{\n"
"border-top: 1px solid #E1E5EA;\n"
"}")
        self.messageInput_widget.setObjectName("messageInput_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.messageInput_widget)
        self.horizontalLayout_4.setContentsMargins(120, -1, 120, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.messageInput_widget)
        self.widget.setMinimumSize(QtCore.QSize(768, 60))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setStyleSheet("background-color: #F6F7F9;\n"
"border:12px;\n"
"border-radius: 8px;\n"
"color:929FB1;\n"
"padding-left: 10px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.uploadfileButton = QtWidgets.QPushButton(self.widget)
        self.uploadfileButton.setMinimumSize(QtCore.QSize(32, 32))
        self.uploadfileButton.setMaximumSize(QtCore.QSize(32, 32))
        self.uploadfileButton.setStyleSheet("background: transparent;\n"
"borders: none;")
        self.uploadfileButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/attach-file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadfileButton.setIcon(icon7)
        self.uploadfileButton.setIconSize(QtCore.QSize(24, 24))
        self.uploadfileButton.setObjectName("uploadfileButton")
        self.horizontalLayout_5.addWidget(self.uploadfileButton)
        self.messageinput = QtWidgets.QTextEdit(self.widget)
        self.messageinput.setStyleSheet("background-color: #F6F7F9;\n"
"border:12px;\n"
"border-radius: 8px;\n"
"color:929FB1;\n"
"padding-top: 15px;\n"
"padding-left: 10px;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-weight: 400;\n"
"line-height: 24px;\n"
"text-align: left;\n"
"")
        self.messageinput.setObjectName("messageinput")
        self.horizontalLayout_5.addWidget(self.messageinput)
        self.sendmessageButton = QtWidgets.QPushButton(self.widget)
        self.sendmessageButton.setMinimumSize(QtCore.QSize(32, 32))
        self.sendmessageButton.setMaximumSize(QtCore.QSize(32, 32))
        self.sendmessageButton.setStyleSheet("background: transparent;\n"
"borders: none;")
        self.sendmessageButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-send-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendmessageButton.setIcon(icon8)
        self.sendmessageButton.setIconSize(QtCore.QSize(32, 32))
        self.sendmessageButton.setObjectName("sendmessageButton")
        self.horizontalLayout_5.addWidget(self.sendmessageButton)
        self.horizontalLayout_4.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.messageInput_widget)
        self.horizontalLayout.addWidget(self.mainChat_widget)
        self.details_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_widget.sizePolicy().hasHeightForWidth())
        self.details_widget.setSizePolicy(sizePolicy)
        self.details_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.details_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.details_widget.setStyleSheet("")
        self.details_widget.setObjectName("details_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.details_widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.details_widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 210))
        self.widget_2.setBaseSize(QtCore.QSize(0, 210))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.XButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XButton.sizePolicy().hasHeightForWidth())
        self.XButton.setSizePolicy(sizePolicy)
        self.XButton.setMinimumSize(QtCore.QSize(32, 32))
        self.XButton.setMaximumSize(QtCore.QSize(32, 32))
        self.XButton.setStyleSheet("background:transparent;\n"
"borders:none;")
        self.XButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-x-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.XButton.setIcon(icon9)
        self.XButton.setIconSize(QtCore.QSize(36, 36))
        self.XButton.setObjectName("XButton")
        self.gridLayout_7.addWidget(self.XButton, 0, 2, 1, 1)
        self.groupedescription = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.groupedescription.setFont(font)
        self.groupedescription.setStyleSheet("padding:20px;")
        self.groupedescription.setObjectName("groupedescription")
        self.gridLayout_7.addWidget(self.groupedescription, 1, 1, 1, 1)
        self.info = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.info.setFont(font)
        self.info.setStyleSheet("padding:10px;")
        self.info.setObjectName("info")
        self.gridLayout_7.addWidget(self.info, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.navigation_widget = QtWidgets.QWidget(self.details_widget)
        self.navigation_widget.setMinimumSize(QtCore.QSize(0, 30))
        self.navigation_widget.setStyleSheet("border-bottom: 1px solid #E1E5EA;\n"
"border-top: 2px solid #E1E5EA;")
        self.navigation_widget.setObjectName("navigation_widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.navigation_widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.imageButtton = QtWidgets.QPushButton(self.navigation_widget)
        self.imageButtton.setStyleSheet("background:transparent;\n"
"border:none")
        self.imageButtton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-image-file-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageButtton.setIcon(icon10)
        self.imageButtton.setIconSize(QtCore.QSize(32, 32))
        self.imageButtton.setObjectName("imageButtton")
        self.horizontalLayout_9.addWidget(self.imageButtton)
        self.fileButton = QtWidgets.QPushButton(self.navigation_widget)
        self.fileButton.setStyleSheet("border:none;\n"
"background:transparent;\n"
"")
        self.fileButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-pdf-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon11)
        self.fileButton.setIconSize(QtCore.QSize(32, 32))
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_9.addWidget(self.fileButton)
        self.verticalLayout_5.addWidget(self.navigation_widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.details_widget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.mediapage = QtWidgets.QWidget()
        self.mediapage.setStyleSheet("*{\n"
"border: 1px solid #E1E5EA;\n"
"}\n"
"\n"
"")
        self.mediapage.setObjectName("mediapage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mediapage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.mediapage)
        self.scrollArea_2.setStyleSheet("*{\n"
"border:none;\n"
"\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px; /* Adjust the width as needed */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #E1E5EA;\n"
"    min-height: 20px; /* Adjust the handle size as needed */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 404, 1077))
        self.scrollAreaWidgetContents_2.setStyleSheet("QLabel{\n"
"height:20px;\n"
"}")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setMinimumSize(QtCore.QSize(207, 207))
        self.label_16.setMaximumSize(QtCore.QSize(207, 207))
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setMinimumSize(QtCore.QSize(207, 207))
        self.label_12.setMaximumSize(QtCore.QSize(207, 207))
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setMinimumSize(QtCore.QSize(207, 207))
        self.label_9.setMaximumSize(QtCore.QSize(207, 207))
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setMinimumSize(QtCore.QSize(207, 207))
        self.label_14.setMaximumSize(QtCore.QSize(207, 207))
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setMinimumSize(QtCore.QSize(207, 207))
        self.label_18.setMaximumSize(QtCore.QSize(207, 207))
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 5, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.mediapage)
        self.filespage = QtWidgets.QWidget()
        self.filespage.setStyleSheet("*{\n"
"border: 1px solid #E1E5EA;\n"
"}")
        self.filespage.setObjectName("filespage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.filespage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.filespage)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.filespage)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.filespage)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.filespage)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 597, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.filespage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.details_widget)
        self.details_widget.raise_()
        self.leftMenu_widget.raise_()
        self.mainChat_widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.chats_stackedwidget.setCurrentIndex(2)
        self.stackedWidget.setCurrentIndex(0)
        self.detailsMenuButton.pressed.connect(MainWindow.showMaximized) # type: ignore
        self.XButton.clicked['bool'].connect(MainWindow.showNormal) # type: ignore
        self.accountButton.clicked['bool'].connect(self.widget_4.show) # type: ignore
        self.hideButton.clicked['bool'].connect(self.widget_4.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Chats"))
        self.promoButton.setText(_translate("MainWindow", " Promo"))
        self.groupeButton.setText(_translate("MainWindow", " Groupe"))
        self.lobbybutton.setText(_translate("MainWindow", " Lobby"))
        self.searchbar.setPlaceholderText(_translate("MainWindow", "Search"))
        self.sendermessagetext_2.setText(_translate("MainWindow", "Hi, Its long time we didn’t messaged, How your work"))
        self.sendermessagetime_2.setText(_translate("MainWindow", "19:45"))
        self.receivermessagetime_2.setText(_translate("MainWindow", "19:45"))
        self.receivermessagetext_2.setText(_translate("MainWindow", "<html><head/><body><p>Hi, Its long time we didn’t messaged, How your work</p><p>asfsdfdfs</p><p>dsfasdfasdf</p></body></html>"))
        self.sendermessagetext.setText(_translate("MainWindow", "Hi, Its long time we didn’t messaged, How your work"))
        self.sendermessagetime.setText(_translate("MainWindow", "19:45"))
        self.receivermessagetext.setText(_translate("MainWindow", "<html><head/><body><p>heloooooooo </p><p>worlddd</p><p><br/></p></body></html>"))
        self.receivermessagetime.setText(_translate("MainWindow", "19:45"))
        self.sendermessagetext_3.setText(_translate("MainWindow", "Hi, Its long time we didn’t messaged, How your work"))
        self.sendermessagetime_3.setText(_translate("MainWindow", "19:45"))
        self.receivermessagetext_3.setText(_translate("MainWindow", "<html><head/><body><p>sasddasd</p></body></html>"))
        self.receivermessagetime_3.setText(_translate("MainWindow", "19:45"))
        self.messageinput.setPlaceholderText(_translate("MainWindow", "Type message"))
        self.groupedescription.setText(_translate("MainWindow", "Groupe description"))
        self.info.setText(_translate("MainWindow", "Info"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
import resources_rc
